feature/remove-dns-records
EncoreTechnologies/stackstorm-menandmice pull request #2
Opened 2019-05-01 21:10 UTC by bishopbm1

Added new actions and workflows to remove a DNS Record and all its related records and PTR records since those are not cleaned up automatically. Added new actions and workflows to test if a hostname is available for use. Added new actions and workflows to test credentials against the server. Iterated pack version and added to changelog.

2019-05-01 23:45 UTC, nmaludy requested changes
Missing README update explaining the new actions

2019-05-02 01:11 UTC, bishopbm1 commented
Updated Readme with explanation and example usages.

2019-05-02 01:12 UTC, nmaludy commented on README.md
> +In addition to the actions above there are a few additional actions that we will discuss here.
"In addition to the auto-generated actions described above, there are a handful of higher-level workflow actions that implement common functionality."

2019-05-02 01:15 UTC, nmaludy commented on README.md
> +
missing resolve_fqdn

2019-05-02 13:22 UTC, bishopbm1 commented
Ah yea sorry forgot about resolve_fqdn.. should be good now though.

2019-05-02 13:30 UTC, nmaludy approved these changes

2019-05-02 13:30 UTC, merged